version: 2.1
jobs:
  build:
    # Replaces NPM with Yarn in CircleCI
    machine:
      environment:
        PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
      node:
        version: v6.11.0
    # docker:
    #   - image: 'circleci/node:latest'

    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn

    test:
      override:
        - yarn test

    steps:
      # - checkout
      - run: echo 'hello world'

general:
  branches:
    only:
     - master
